export const locCellsData = [
  {
    type: "frontEnd",
    tape: "article",
    sub: "javascript",
    hed: "Front-End",
    body: "using react with typescript and webpack",
    bottom: "Javascript",
    list: ["javascript", "css", "html", "webpack"],
  },
  {
    type: "frontEnd",
    tape: "article",
    sub: "html",
    hed: "Front-End",
    body: "html with js and css",
    bottom: "Html",
    list: ["html", "css", "webpack"],
  },
  {
    type: "frontEnd",
    tape: "article",
    sub: "css",
    hed: "Front-End",
    body: "ways to convert scss to css",
    bottom: "Css-Scss",
    list: ["html", "css", "webpack", "commandline"],
  },
  {
    type: "frontEnd",
    tape: "article",
    sub: "react",
    hed: "Front-End",
    body: "using react with typescript and webpack",
    bottom: "React",
    list: ["javascript", "scss", "redux", "webpack"],
  },

  {
    type: "backEnd",
    tape: "code",
    sub: "mongoDB",
    hed: "Back-End",
    body: "mongoDB bases info to use it",
    bottom: "MongoDB",
    list: ["nodeJS", "javascript", "html", "css", "mongoDB"],
  },
  {
    type: "backEnd",
    tape: "code",
    sub: "sql",
    hed: "Back-End",
    body: "how to start sql",
    bottom: "SQL",
    list: ["nodeJS", "javascript", "html", "sql", "mongoDB"],
  },
  {
    type: "backEnd",
    tape: "code",
    sub: "nodejs",
    hed: "Back-End",
    body: "start server locally",
    bottom: "NodeJs",
    list: ["nodeJS", "javascript", "html", "css"],
  },
  {
    type: "backEnd",
    tape: "code",
    sub: "php",
    hed: "Back-End",
    body: "start server locally",
    bottom: "Php",
    list: ["php", "javascript", "html", "scss"],
  },
  {
    type: "backEnd",
    tape: "code",
    sub: "python",
    hed: "Back-End",
    body: "start server locally",
    bottom: "Python",
    list: ["python", "javascript", "html", "scss"],
  },
  {
    type: "backEnd",
    tape: "code",
    sub: "postgres",
    hed: "Back-End",
    body: "mongoDB with nodeJs, react and typescript",
    bottom: "Postgres",
    list: ["nodeJS", "typescript", "postgres"],
  },

  {
    type: "tools",
    tape: "article",
    sub: "webstorm",
    hed: "Tools",
    body: "prettier on save",
    bottom: "Webstorm",
    list: ["webstorm", "javascript"],
  },
  {
    type: "tools",
    tape: "article",
    sub: "github",
    hed: "Tools",
    body: "easy commit and push to github using commandline",
    bottom: "Github",
    list: ["github", "commandline", "webstorm"],
  },
  {
    type: "tools",
    tape: "article",
    sub: "pycharm",
    hed: "Tools",
    body: "easy commit and push to github using commandline",
    bottom: "PyCharm",
    list: ["commandline", "pycharm"],
  },
  {
    type: "tools",
    tape: "article",
    sub: "vscode",
    hed: "Tools",
    body: "easy commit and push to github using commandline",
    bottom: "VSCode",
    list: ["commandline", "vscode"],
  },

  {
    type: "others",
    tape: "code",
    sub: "gsap",

    hed: "Others",
    body: "use gsap and make animation much better",
    bottom: "Gsap",
    list: ["webstorm", "gsap", "html", "css"],
  },
];
