export const locCellsData = [
  {
    type: "front-end",
    sub: "js",
    hed: "Front-End",
    body: "using react with typescript and webpack",
    bottom: "Javascript",
    list: ["javascript", "css", "html", "webpack"],
  },
  {
    type: "back-end",
    sub: "nodejs",
    hed: "Back-End",
    body: "start server locally",
    bottom: "NodeJs",
    list: ["nodeJS", "js", "html", "css"],
  },
  {
    type: "front-end",
    sub: "react",
    hed: "Front-End",
    body: "using react with typescript and webpack",
    bottom: "React",
    list: ["javascript", "scss", "redux", "webpack"],
  },
  {
    type: "tools",
    sub: "webstorm",
    hed: "Tools",
    body: "prettier on save",
    bottom: "Webstorm",
    list: ["webstorm", "js"],
  },
  {
    type: "tools",
    sub: "github",
    hed: "Tools",
    body: "easy commit and push to github using commandline",
    bottom: "Github",
    list: ["github", "commandline", "webstorm"],
  },
  {
    type: "front-end",
    sub: "html",
    hed: "Front-End",
    body: "html with js and css",
    bottom: "Html",
    list: ["html", "css", "webpack"],
  },
  {
    type: "front-end",
    sub: "css",
    hed: "Front-End",
    body: "ways to convert scss to css",
    bottom: "Css-Scss",
    list: ["html", "css", "webpack", "commandline"],
  },
  {
    type: "others",
    sub: "gsap",
    hed: "Others",
    body: "use gsap and make animation much better",
    bottom: "Gsap",
    list: ["webstorm", "gsap", "html", "css"],
  },
  {
    type: "back-end",
    sub: "mongoDB",
    hed: "Back-End",
    body: "mongoDB bases info to use it",
    bottom: "MongoDB",
    list: ["nodeJS", "js", "html", "css", "mongoDB"],
  },
  {
    type: "back-end",
    sub: "mongoDB",
    hed: "Back-End",
    body: "mongoDB with nodeJs, react and typescript",
    bottom: "MongoDB",
    list: ["nodeJS", "typescript", "react", "mongoDB"],
  },
];
